name: Bug report
description: Create a report to help us improve
title: "Bug Report"
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please check [existing issues](https://github.com/shexjs/shex.js/issues) to avoid duplication.
  - type: dropdown
    id: browser
    attributes:
      label: What broken?
      multiple: true
      options:
        - shexjs in node
        - shexjs in browser
        - Typescript types
        - ShEx WebApp
        - ShExMap WebApp
        - Other (specify in text)
  - type: textarea
    id: version
    attributes:
      label: Version
      description: Specify the version of shexjs you are using (`npm list | grep @shexjs` may give you multiple results)
      render: plain text
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened (e.g., it crashed)?
      description: What was the unexpected behavior? Please add any relevant screenshots (but avoid sharing personal or sensitive information).
      placeholder: e.g. dense black smoke
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should have happened instead (e.g., it shouldn't crash)?
      description: What was the *expected* behavior?
      placeholder: e.g. light browning of bread
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How can we reproduce this error?
      description: What steps can we take to reproduce this error?
      placeholder: e.g. insert in toaster and press lever
    validations:
      required: false
#  - type: textarea
#    id: logs
#    attributes:
#      label: Relevant log output
#      description: Please copy and paste any relevant log output, e.g. f`DEBUG=*`. This will be automatically formatted into code, so no need for backticks.
#      render: plain text
