blank_issues_enabled: false
contact_links:
  - name: FDP Reference Implementation
    url: https://github.com/FAIRDataTeam/FAIRDataPoint
    about: If you have an issue with FDP Reference Implementation, please check its own GitHub repository.
